name: pre-commit

on:
  pull_request:
  push:
    branches: [main]
    paths-ignore:
      - README.md
      - LICENSE
      - '.github/**'

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version-file: go.mod
    - name: Install Golang pre-commit dependencies
      run: |
        go install golang.org/x/tools/cmd/goimports@latest
        go install github.com/fzipp/gocyclo/cmd/gocyclo@latest
        curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.55.2
        go install -v github.com/go-critic/go-critic/cmd/gocritic@latest
    - name: Setup Python v3
      uses: actions/setup-python@v4
    - name: Run pre-commit
      uses: pre-commit/action@v3.0.0
