name: test
on:
  push:
    branches: [main]
    paths-ignore:
      - README.md
      - '.github/**'

permissions:
  contents: write

jobs:
  test:
    name: Test Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
      - name: Test
        run: |
          go test -timeout=3s -race -count=10 -failfast -shuffle=on -short ./...
          go test -timeout=10s -race -count=1 -failfast  -shuffle=on ./...
      - name: Generate Test Coverage
        run: go test ./... -coverprofile=./cover.out -covermode=atomic -coverpkg=./...
      - name: Check Test Coverage
        uses: vladopajic/go-test-coverage@v2
        with:
          config: ./.github/.testcoverage.yml
          git-branch: badges
          git-token: ${{ github.ref_name == 'main' && secrets.GITHUB_TOKEN || '' }}
